### ISSUE TITLE
Question about defaultIndex

### ISSUE THREAD

**Issue by denisvely** [vdor/react-native-horizontal-picker#11]
HI, Vseslav Dorofeev

i`m experiencing problem with default index.

I will attach screenshots to be more clear and i will provide simple example of what i should do and what is the actual behavior.

That`s my code:
------------------------
const Items = Array.from(Array(10).keys());

const rednerItem = (item, index) => (
  <View style={[styles.item], { width: 80, borderWidth: 1, borderColor: 'red' }}>
      <Text style={{textAlign: 'center'}}>
      { item }
      </Text>
  </View>
  );

 <HorizontalPicker
      data={Items}
      renderItem={rednerItem}
      itemWidth={80}
      defaultIndex={9}
  />
------------------------
**This is how it looks on mount of the component:**
![image](https://user-images.githubusercontent.com/28669083/116437089-bc505580-a855-11eb-812c-c37f8ed163c7.png)

**This is what i espect to be on mount of the component:**

![image](https://user-images.githubusercontent.com/28669083/116437178-d8ec8d80-a855-11eb-9d22-6b5b75a4ccd0.png)

Thanks in advance!

**Comment by vdor** [comment]
Hey @denisvely !

Thanks for the info! Yes, I see. I'm going to make patch with fix today

**Comment by vdor** [comment]
@denisvely Try to use this version of the lib - `^0.1.1`

**Comment by denisvely** [comment]
@vdor Thank you!
It is working perfect!
