### ISSUE TITLE
Change value dynamically

### ISSUE THREAD

**Issue by RicardoDolNL** [vdor/react-native-horizontal-picker#47]
Hi,

Is it possible to use the scrollTo function or something else to change the value dynamically?
I want to change the selected value/position after the component is already loaded.

**Comment by vdor** [comment]
Hi!

You can try to make a ref to `HorizontalPicker` and get access to the method `scrollToPosition(position: number)` using `yourRef.current.scrollToPosition(yourPosition)`

**Comment by RicardoDolNL** [comment]
I've decided to create my own custom picker, but thnx for the response!
